### ISSUE TITLE
how to reproduce the experiments in the Granite paper?

### ISSUE THREAD

**Issue by ronghongbo** [google/gematria#118]
Hello, this is not an issue, but a question how to reproduce the experiments in Table 5 or 6 in the IISWC'22 Granite paper. Specific instructions would be greatly appreciated.
Hongbo

**Comment by ondrasej** [comment]
Hello, and thanks for reaching out.

The experimentes were done using the data set from the [Ithemal paper](https://arxiv.org/abs/1808.07412) which unfortunately can't be published due to license restrictions. The hyperparameters of the winning models are mentioned in the paper, but I'll try to dig out additional details sometimes this week.

**Comment by ronghongbo** [comment]
Understood. Thanks, Ondrej!
Hongbo

**Comment by boomanaiden154** [comment]
Now that most of the infrastructure has been implemented for large dataset collection, creating a dataset similar to what was described in the original Ithemal paper should be possible. The datasets won't exactly match due to differing environments/compilers/software versions, but I would think the results would end up being comparable. There will also be differences in the collection infrastructure that might produce tangible effects. There are at least some fixes that still need to be done regarding how benchmarking subprocesses get scheduled across NUMA nodes.

There are also a lot of patches sitting in PRs to enable the necessary flows that have just been sitting there. I need to finish those up and get them landed. That should start happening a week from Friday.

We also need to get some documentation written on a full training flow. Once the full training flow is working, I can probably work on writing something up.

**Comment by ronghongbo** [comment]
Sounds great!

**Comment by ondrasej** [comment]
Here are the parameters used in the best model from the paper (multi-task, IVB+HSW+SKX trained at the same time, GNN + 5% unknown token injection):

**Model parameters:**
```python
gematria_throughput_source_filter = [
      'ithemal: kind=KIND_MEASURED, uarch=ARCH_SKYLAKE',
      'ithemal: kind=KIND_MEASURED, uarch=ARCH_HASWELL',
      'ithemal: kind=KIND_MEASURED, uarch=ARCH_IVYBRIDGE',
  ]
gematria_task_names = ['skx', 'hsw', 'ivb']
gematria_node_embedding_size = 256
gematria_node_update_layers = '256, 256'
gematria_edge_embedding_size = 256
gematria_edge_update_layers = '256, 256'
gematria_global_embedding_size = 256
gematria_global_update_layers = '256, 256'
gematria_readout_layers = ''
gematria_task_readout_layers = '256, 256'
gematria_rnn_output_size = 0
gematria_rnn_bidirectional = False
gematria_rnn_type = 'NONE'
gematria_num_message_passing_iterations = 4
gematria_use_sent_edges = True
gematria_graph_module_layer_normalization = True
gematria_readout_input_layer_normalization = True
gematria_task_readout_input_layer_normalization = True
gematria_graph_module_residual_connections = True
gematria_readout_residual_connections = True
gematria_task_readout_residual_connections = True
gematria_seq2seq = True
gematria_use_seq2seq_loss = False
gematria_loss_type = 'MEAN_ABSOLUTE_ERROR'
gematria_loss_normalization = 'PERCENTAGE_ERROR'
gematria_collected_percentile_ranks = '50,90,95,99'
```
**Training process flags:**
```python
gematria_action = 'train'
gematria_max_blocks_in_batch = 100
gematria_max_instructions_in_batch = None
gematria_checkpoint_max_to_keep = 100
gematria_synchronous_training = True
gematria_training_num_epochs = -1
gematria_rnn_dropout = 0.0
gematria_training_randomize_batches = True
gematria_num_training_worker_replicas = 1
gematria_num_training_shards = 49
gematria_learning_rate = 0.001
gematria_decay_steps = 0
gematria_decay_rate = 0.0
gematria_out_of_vocabulary_injection_probability = 0.05
gematria_learning_rate_schedule = 'NONE'
```

I've skipped anything related to input/output files because those will be different in your case anyway. All other flags were at their default values.

**Comment by ronghongbo** [comment]
That is great! Thanks, Ondrej!
Hongbo
