### ISSUE TITLE
Incompatibility with Python 3.12

### ISSUE THREAD

**Issue by virajbshah** [google/gematria#122]
Python 3.12 supports only TensorFlow 2.16 - which drops the `tf.estimator` API, used by the current version of `tensorflow-ranking` used in Gematria. Until `tensorflow-ranking` [gains compatibility](https://www.tensorflow.org/guide/migrate/migrating_estimator) with TensorFlow 2.16 (and hence Python 3.12), we'll have to stick with Python 3.11 and TensorFlow 2.15.

**Comment by ondrasej** [comment]
A few thoughts on this:
- we need the code to stay compatible with Python 3.11 anyway (due to internal limitations). But that doesn't mean that we need to block upgrading to TF 2.16.
- IIRC, the `tf.estimator` API is used only by the ranking loss, which was an experiment that didn't really work well (the MAPE/MSPE losses work a lot better). If it's still the case, I'd be for removing the ranking loss and getting rid of the `tensorflow-ranking` dependency which will also simplify our dependency structure and deployment process.

WDYT? And would you like to take a look at this?

**Comment by virajbshah** [comment]
Removing `tensorlow-ranking` should be an easy choice if the ranking loss is not very effective, especially since it'll make installation/set-up a little simpler since there won't be a separate process for MacOS.

I can look into it, but I think it will stay low priority since it isn't blocking anything (other than TF 2.16).

**Comment by virajbshah** [comment]
Turns out removing `tfr` was very straightforward. I have left the PR (#128) with the corresponding changes as a draft in case we think any further discussion about whether it should be kept around or not is in order.

**Comment by boomanaiden154** [comment]
It seems reasonable enough to me, and not being able to upgrade to TF 2.16 I think is pretty good motivation to just remove the functionality. I'd say open the PR for review and ping reviewers.

**Comment by virajbshah** [comment]
Fixed by PR #128
